#!/usr/bin/env bash
# checking for command line arguments


if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

#disabbling Strict Host Key checking
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_path" "$username@$ip:~/"

#checking if the trandfer was succesful
if [ $? -eq 0]
then
	echo "FILE TRANSFER WAS SUCCESSFULL"
else
	echo "FILE TRANFER FAILES"
fi
